### ISSUE TITLE
Testing pylablib with Princeton Cameras

### ISSUE THREAD

**Issue by LMSC-NTappy** [AlexShkarin/pyLabLib#11]
Hello,
 
I have started using pylablib last week and so far it's been a great experience, so I just wanted to say many thanks for your work! 

I just read #2 and wanted to let you know that I have access to 2 PyLon cameras (Br_eXcelon). So far I am able to grab frames and it seems setting some basic settings. I will let you know if I encounter any problems.

But mostly, let me know if you want me to test anything in particular, I am more than happy to help

**Comment by AlexShkarin** [comment]
Hello,

Thank you for the kind words! I'm glad to know that everything seems to be working out for now.

Also, thank you for the offer! I would let you know whenever there are updates to the Princeton Instruments cameras, so you could test them (and also, hopefully, find them useful).

**Comment by LMSC-NTappy** [comment]
Hello,


>Also, thank you for the offer! I would let you know whenever there are updates to the Princeton Instruments cameras, so you could test them (and also, hopefully, find them useful).

Always pleasure! I am closing this issue now :)
