### ISSUE TITLE
"SerialException: Port is already open" in Attocube.ANC300

### ISSUE THREAD

**Issue by qyangcaltech** [AlexShkarin/pyLabLib#2]
Hi!
Here is the connection that I have tried. I disabled the serial port and enabled before this line, but it still give the SerialException: port is already open. I'm wondering whether there is redundant port opening instruction in the code somewhere that we need to disable that? Or is there anything I need to watch out for to connect to ANC300?

Thanks!

In [3]: anc=Attocube.ANC300("COM3")
---------------------------------------------------------------------------
SerialException                           Traceback (most recent call last)
<ipython-input-3-54a2255cc088> in <module>()
----> 1 anc=Attocube.ANC300("COM3")

~\pyLabLib\pylablib\aux_libs\devices\Attocube.py in __init__(self, conn, backend
, pwd)
     30         self.pwd=pwd
     31         backend_mod.IBackendWrapper.__init__(self,instr)
---> 32         self.open()
     33         self._correction={}
     34         self._add_settings_node("voltages",self.get_all_voltages,self.se
t_all_voltages)

~\pyLabLib\pylablib\aux_libs\devices\Attocube.py in open(self)
     39     def open(self):
     40         """Open the connection to the stage"""
---> 41         res=self.instr.open()
     42         if self.instr._backend=="network" and self.pwd is not None:
     43             self.instr.write(self.pwd)

~\pyLabLib\pylablib\core\devio\backend.py in open(self)
    447             """Open the connection."""
    448             if not self._connect_on_operation:
--> 449                 self._do_open()
    450             self.opened=True
    451         def close(self):

~\pyLabLib\pylablib\core\devio\backend.py in _do_open(self)
    440
    441         def _do_open(self):
--> 442             general.retry_wait(self.instr.open, self._open_retry_times,
0.3)
    443         def _do_close(self):
    444             #general.retry_wait(self.instr.flush, self._open_retry_times
, 0.3)

~\pyLabLib\pylablib\core\utils\general.py in retry_wait(func, try_times, delay,
exceptions)
    360     for t in RetryOnException(try_times,exceptions):
    361         with t:
--> 362             return func()
    363         if delay>0:
    364             time.sleep(delay)

~\Anaconda\lib\site-packages\serial\serialwin32.py in open(self)
     39             raise SerialException("Port must be configured before it can
 be used.")
     40         if self.is_open:
---> 41             raise SerialException("Port is already open.")
     42         # the "\\.\COMx" format is required for devices other than COM1-
COM8
     43         # not all versions of windows seem to support this properly

SerialException: Port is already open.

**Comment by AlexShkarin** [comment]
I apologize for getting back to you so late.

You are right, there is a redundant opening command in the ANC300 class. I only tested it with the network connection, where this does not cause an error.

The issue should now be fixed.
