### ISSUE TITLE
BSC201 does not detect as correct model

### ISSUE THREAD

**Issue by Frnot** [AlexShkarin/pyLabLib#21]
I am attempting to control an HDR50 stage from a BSC201 it has a serial number of 40163084.

When I attempt to run `Thorlabs.KinesisMotor("40163084")` I get the following error:

```
UserWarning: model number SCC201 doesn't match the device ID prefix 40(BSC101)
  warnings.warn("model number {} doesn't match the device ID prefix {}({})".format(model_no,port,port_model_no))
UserWarning: can't recognize motor model SCC201; setting all scales to internal units
  warnings.warn("can't recognize motor model {}; setting all scales to internal units".format(model))
```
  
 I suppose I could ignore this easy enough, but I'd like to have accurate scaling when controlling the stage. Is there any way I can set my device parameters manually?

**Comment by AlexShkarin** [comment]
There's an option to supply scale in the constructor as a tuple ``(position_scale, velocity_scale, acceleration_scale)``, which gives ratio of the physical units to the internal units. For example, for a rotational stage a single physical degree corresponds to ``position_scale`` internal units (usually, motor microsteps).

As far as I can see from the manual, for HDR50 stage controlled by a BSC20x driver these scales are ``(75091, 4030885, 826)``, which make all units expressed in degrees (or in units of 0.99997 degrees; documentation is a bit unclear on that, so you'll need to test it yourself if you care about that kind of precision). Hence, to get the correct units you need to execute
```python
stage = Thorlabs.KinesisMotor('40163084', scale = (75091, 4030885, 826))
```
Let me know if that works for you.
