### ISSUE TITLE
handle for Arcus

### ISSUE THREAD

**Issue by aesatchien** [AlexShkarin/pyLabLib#3]
Hello Alex,
First, thank you for the great work you are doing.  I've been trying to use the Arcus from the dev branch for a few days and I have an issue.  I have attached an ipython session.  I'm using version 3.7.  I don't have any problems running the Arcus.PerformaxStage() to give me an object, and I can get the device_id and that all looks good - same 2ed00 address and index 0 that the vendor's windows GUI reports.  So I believe the dll is communicating just fine. 
However, the rbuff never gets updated when using the query() function or anything that calls it.  Similarly, close() fails due to the timeout. 
I am certainly not an expert at python.  But just from troubleshooting this,  I am guessing that since 1) the functions that aren't working require the handle, and 2) the working functions that don't require a handle are updating the rbuff properly,  is it possible that the python 3x version is not getting the Arcus handle correctly during the open function?

Thank you again for your time.
-Cory

### 

	Python 3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]
	Type 'copyright', 'credits' or 'license' for more information
	IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.
	In [3]: import pylablib
	In [4]: Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
	   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
	   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
	   QT_SCALE_FACTOR to set the application global scale factor.
	In [4]: from pylablib.aux_libs.devices import Arcus  # import the device libraries
	In [5]: myArcus = Arcus.PerformaxStage()
	In [6]: myArcus.get_devices_num()
	Out[6]: 1
	In [7]: myArcus.get_device_id()
	Out[7]:
	['2ed00',
	 'Performax USB',
	 '\\\\?\\usb#vid_1589&pid_a101#2ed00#{3c5e1462-5695-4e18-876b-f3f3d08aaf18}',
	 '1589',
	 'a101']
	In [8]: myArcus.rbuff.value
	Out[8]: b'a101'
	In [9]: myArcus.get_position("X")
	---------------------------------------------------------------------------
	ValueError                                Traceback (most recent call last)
	<ipython-input-9-14cc77bd524a> in <module>()
	----> 1 myArcus.get_position("X")

	~\automation\pylablib\pylablib\aux_libs\devices\Arcus.py in get_position(self, axis)
		144         """Get the current axis position"""
		145         axis=self._check_axis(axis)
	--> 146         return int(self.query("P"+axis))
		147     def set_position_reference(self, axis, position=0):
		148         """

	ValueError: invalid literal for int() with base 10: 'a101'

	In [10]: myArcus.rbuff.value
	Out[10]: b'a101'
	In [11]: myArcus.handle
	Out[11]: -1380944000
	In [12]: myArcus.close()
	---------------------------------------------------------------------------
	ArcusError                                Traceback (most recent call last)
	<ipython-input-12-994961cdf0e2> in <module>()
	----> 1 myArcus.close()

	~\automation\pylablib\pylablib\aux_libs\devices\Arcus.py in close(self)
		 82                     return
		 83                 time.sleep(0.3)
	---> 84             raise ArcusError("can't disconnect from the stage with index {}".format(self.idx))
		 85     def is_opened(self):
		 86         return self.handle is not None

	ArcusError: can't disconnect from the stage with index 0

**Comment by AlexShkarin** [comment]
You are correct, it seems to be a problem with the handle. It is treated as a 4-byte signed in the pylablib code, but it looks like it should be 8-byte on 64-bit systems (this would also explain why the handle is negative, which could indicate overflow). I updated the code to treat it as an 8-byte unsigned integer on 64-bit systems. Please, let me know if it started working for you.

Alexey.

**Comment by aesatchien** [comment]
Perfect!  I can now issue queries and get the stage's information.  Thank you for fixing that.  It is definitely working for me now for everything I need to do.

A few minor notes to make sure everything works as you intended: on my stage, the command for speed is "HSPD", and the code currently has "HS".  For me .get_axis_speed("X") and its variants will fail returning a   '?HSX' but a .query("HSPDX") will give the correct number back.  Also, I only have two axes on my controller so .get_full_status() and .get_full_info() will similarly raise errors when it asks for "PZ" as shown below.  I'm not sure if the .get_devices_num() or the query on "ID" returning 'Performax-2ED-SA' may help with that to know to only ask for X and Y.  
Also, could you please tell me how you intend for the class nodes to be updated and read?  I can't tell from looking at the code if there is a simple way to access them. 
Thanks again,
-Cory

	$ !w
	winpty ipython
	Python 3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]
	Type 'copyright', 'credits' or 'license' for more information
	IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

	In [1]: import sys
	   ...: sys.path.insert(0, './pyLabLib')
	   ...: import pylablib
	   ...: from pylablib.aux_libs.devices import Arcus
	   ...:
	   ...:

	In [2]: Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
	   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
	   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
	   QT_SCALE_FACTOR to set the application global scale factor.
	In [2]:

	In [2]: myArcus = Arcus.PerformaxStage()

	In [3]: myArcus.query("HSX")
	Out[3]: '?HSX'

	In [4]: myArcus.query("HSPDX")
	Out[4]: '4000'

	In [5]: myArcus.query("ID")
	Out[5]: 'Performax-2ED-SA'

	In [6]: myArcus.get_devices_num()
	Out[6]: 1

	In [7]: myArcus.query("PX")
	Out[7]: '8000'

	In [8]: myArcus.query("PZ")
	Out[8]: '?PZ'

	In [9]: myArcus.get_full_info()
	---------------------------------------------------------------------------
	ValueError                                Traceback (most recent call last)
	<ipython-input-9-faabec32b2b6> in <module>()
	----> 1 myArcus.get_full_info()

	~\automation\pyLabLib\pylablib\core\devio\interface.py in get_full_info(self, nodes)
		119         `nodes` specifies nodes to acquire.
		120         """
	--> 121         return self._get_info(["settings","status","full_info"],nodes=nodes)
		122     def apply_settings(self, settings):
		123         """

	~\automation\pyLabLib\pylablib\core\devio\interface.py in _get_info(self, kinds, nodes)
		 95                     if g:
		 96                         try:
	---> 97                             info[k]=g()
		 98                         except err+self._nodes_ignore_error["get"]:
		 99                             pass

	~\automation\pyLabLib\pylablib\core\devio\interface.py in func_mux(args)
		 44                 return res
		 45             else:
	---> 46                 return [func(ch) for ch in choices]
		 47         return func_mux
		 48     def _add_info_node(self, path, kind, getter=None, setter=None, ignore_error=(
	), mux=None, multiarg=True):

	~\automation\pyLabLib\pylablib\core\devio\interface.py in <listcomp>(.0)
		 44                 return res
		 45             else:
	---> 46                 return [func(ch) for ch in choices]
		 47         return func_mux
		 48     def _add_info_node(self, path, kind, getter=None, setter=None, ignore_error=(
	), mux=None, multiarg=True):

	~\automation\pyLabLib\pylablib\aux_libs\devices\Arcus.py in get_position(self, axis)
		145         """Get the current axis position"""
		146         axis=self._check_axis(axis)
	--> 147         return int(self.query("P"+axis))
		148     def set_position_reference(self, axis, position=0):
		149         """

	ValueError: invalid literal for int() with base 10: '?PZ'

**Comment by AlexShkarin** [comment]
Cory,

Thank you for pointing it out, I didn't realize that the command systems differ so much between different Arcus stages. Unfortunately, since I only have 4EX stage in my posession, I don't think it would be

**Comment by aesatchien** [comment]
Hi Alexy, 
Thank you again for supporting this.  I have been using the original Arcus for the past several weeks.  Since query works, I have been able to get everything running smoothly and haven't tried looking for more issues.  I'll look at the new version and if I run into anything I'll let you know.
Best,
-Cory

**Comment by ThomasPujolle** [comment]
Good morning,

I have been using LabView (32bits) drivers from Arcus to control my rotary stages and it seems I'm facing a similar issue with the handle. For about 3h the equipment run fine, this is equivalent to about 400 connection opened then closed. The handles usually looks like this:
867545864, 867555384

Then one connection gets negative handles:
-1981291816,-1981291136

All operations run fine but the connection cannot be closed because handle are negative and then the system hangs.

You mentioned that you fixed this in python by making the handle 8-byte long on 64 bits system, would that be a fix for me too? I am running 32bits LabView on a 64bits system, the prototype of the method called is as follow:
`int32_t _fnPerformaxComOpen@8(int32_t deviceIndex, int32_t *reference);`

The return type is consistent in LabView, it's a I32 (long).

Although I am on a 64bits system the return handle should be of the type specified in the prototype right?

Any help much appreciated since it's more a numeration/representation issue than juste Python or Labview.

Thanks

**Comment by AlexShkarin** [comment]
In principle, this can be the reason, but I can't seem to reproduce this behavior in Python (32 bit version running on 64 bit OS). I always get handler which is below 2^31 (i.e., it can't overflow), even if I open/close Arcus multiples (1000) times, or try to fill RAM with data (it runs out of memory before it returns such handle). The only thing I could recommend is to convert signed integers into unsigned (i.e., use uint32_t instead of int32_t), at least in the methods where it freezes/fails, and see if this helps.

I'm sorry I couldn't be of more help.
