### ISSUE TITLE
Hamamatsu synchronous readout mode

### ISSUE THREAD

**Issue by Winounet** [AlexShkarin/pyLabLib#47]
Hi, 
Thanks a lot for pylalib, it helped me create a software to control easily my Hamamatsu ORCA Flash (C11440-22CU). Unfortunately I cannot find either in the API and in Pylablib if the mode "synchronous readout" in trigger exists ? 
I can get internal trigger or external trigger and within the latter there is only level or edge trigger but the third one, synchronous readout is, to my knowledge not accessible. The Synchronous readout mode is made to get a continuous acquisition without having a global "readout time" in rolling shutter. 
Are you aware of such a mode in the API or have you developed this in pylablib and I did not noticed ? 
Thank you very much
Antoine

**Comment by AlexShkarin** [comment]
Hello!

This is not implemented directly as a method of the class, but, as far as I can see, you can still access it via the camera attribute ``"trigger_active"``:
```python
print(cam.ca["trigger_active"].labels)  # this should print all values supported by the camera
cam.cav["trigger_active"]=3  # this is the SYNCREADOUT trigger
```
This seems to work on ``C11440-22CU`` with camera version ``2.60.A``
If this attribute or this value is not accessible, it could be that it is not supported by your camera. In that case, you can check if it is available in the native software (e.g., HOKAWO).

Sincerely,

Alexey
