### ISSUE TITLE
KDC 101 Error Backend exception: D2XXException(3) ('Device Not Opened')

### ISSUE THREAD

**Issue by zurminal** [AlexShkarin/pyLabLib#5]
Hello, 

Firstly, thanks a lot for the great work done on this. Stumbled across it while trying to automate certain thorlabs stages and I believe it will be very useful. 

I am running into issues with connecting the stage. I am able to detect the controller (KDC101 - Brushed Motor Controller) that is connected. 

<img width="378" alt="image" src="https://user-images.githubusercontent.com/95460899/144546539-f03b669c-875f-4df0-89d9-09aea58da211.png">

However, when I connect to the stage, I get the following error 

<img width="412" alt="image" src="https://user-images.githubusercontent.com/95460899/144546752-a90b77f3-3f85-41d6-968a-812730039659.png">

<img width="649" alt="image" src="https://user-images.githubusercontent.com/95460899/144546718-a2fea1a6-809a-4f37-b2f7-78b9898a443c.png">

Please any insights into why I am getting this error will be appreciated.

**Comment by AlexShkarin** [comment]
Hello!

This error should not normally show up, and I have not personally seen it before. It seems like it might be realted to problems with FTDI drivers, especially on Linux or MacOS. For example, such error is discussed [here](https://stackoverflow.com/questions/28461433/unable-to-open-a-connection-to-an-ftdi-device) or [here](https://github.com/thomaschaaf/node-ftdi/issues/4). Some other reports [here](https://www.edaboard.com/threads/problem-with-d2xx-as-it-cant-open-jtag.127837/) or [here](https://forums.raspberrypi.com/viewtopic.php?t=159181) also suggest that it might be related to permissions (i.e., you need to run the code as root). Unfortunately, I could not find any more information so far.

In case you're using Windows, I have one more suggestion: can you install [Thorlabs APT software](https://www.thorlabs.de/software_pages/ViewSoftwarePage.cfm?Code=Motion_Control&viewtab=1) and confirm that you can connect to the stage from there?

Sincerely,

Alexey.

**Comment by zurminal** [comment]
Hi Alex, 

Thanks I was able to rectify it. After connecting to the stage once and not closing that connection, re attempting to connect leads to that error. I now have stage.close() in all my code blocks and that seems to solve the problem. 

Thanks a lot for the suggestions and helping to look into this :).
