### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'loads'

### ISSUE THREAD

**Issue by SirNate0** [AlexShkarin/pyLabLib#9]
Per numpy release notes, numpy.loads is deprecated and should be replaced with pickle.loads. Presumably it has been removed as of numpy 1.22, which is the version that was installed by pip on my system.

https://numpy.org/doc/1.21/release/1.15.0-notes.html?highlight=loads

**Comment by AlexShkarin** [comment]
Thank you for pointing this out! It is fixed in the new release (1.3.3).
